In [1]:
from transformer import Cross
import numpy as np

In [2]:
X = np.array([
    [-1, 1, 2, 1, -2],
    [-1, 0, 1, 0, -1]
]).T

exp = np.array([
    [1, 0, 0, -1],
    [0, 1, 0, -1]
]).T

X.shape

(5, 2)

In [3]:
Cross().fit_transform(X)

array([[ 0,  0],
       [ 1,  0],
       [ 0,  1],
       [ 0,  0],
       [-1, -1]])

In [4]:
np.sign(X)

array([[-1, -1],
       [ 1,  0],
       [ 1,  1],
       [ 1,  0],
       [-1, -1]])

In [5]:
np.sign(np.diff(np.sign(X), axis=0))

array([[ 1,  1],
       [ 0,  1],
       [ 0, -1],
       [-1, -1]])

In [6]:
out = np.sign(np.diff(np.sign(X), axis=0)) * (X[1:, :] != 0)

In [7]:
np.vstack([np.zeros(np.shape(X)[1], dtype=np.int8).reshape(1, -1), out])

array([[ 0,  0],
       [ 1,  0],
       [ 0,  1],
       [ 0,  0],
       [-1, -1]])

In [8]:
np.zeros(np.shape(X)[1]).reshape(1, -1).shape, out.shape

((1, 2), (4, 2))